services:
  - type: web
    name: indian-banks-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: indian-banks-db
          property: connectionString

databases:
  - name: indian-banks-db
    databaseName: indian_banks
    user: indian_banks_user 